### ISSUE TITLE
Analyze the Purity of Our Distillate

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#1069]
We have refined! How pure is our output?

To answer this question, we need to build a few new tool to analyze our purity.

This will involve:
- Size Calculation/Visualization of the ZF Compendium before and after filtering and imputation steps
- Interactive display with `bokeh` showing metadata upon hover
- Full-resolution visualization with Dask+Matplotlib
- Sorts/clustering
- Load metadata into Dataframes and generate statistics of metadata representation
- Train simple sex/type/disease state classifier

**Comment by cgreene** [comment]
@jaclyn-taroni has some info on this from her analysis of the compendium that she got. It looked like there was some large technical difference in some of the RNA-seq samples. My guess was that it was rRNA depletion vs poly-A selection (since some of them looked more like the arrays). Nailing this down is probably the first step to all of the above.

**Comment by jaclyn-taroni** [comment]
I agree that tracking down the technical difference in RNA-seq samples is the first step. If we tackle #731, that's going to be helpful with transparency because the repo with those analyses is necessarily private at the moment.
