### ISSUE TITLE
Links to Author/Institution search from experiment page aren't effective/helpful

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#1271]
### Context
 Something we should consider before we drop the beta label

### Problem or idea

The accuracy of Author Name and Institution search is very low. While the concept of linking Author Names and Institution to the search is good, the problem is that the search results aren't relevant to be useful. If anything, it makes it seem like the search is broken. 

### Solution or next step

We should unlink them for now. 
Tagging @arielsvn to figure out if we can leverage elastic search options to improve the accuracy/relevancy of the search with author names and institution.

**Comment by wvauclain** [comment]
This was partially fixed by Alexslemonade/refinebio-frontend#709, but until the general search performance improves I think we should keep this open. Specifically, once we support quoted phrases, we should go back and modify the code from 709 to use this instead: `publication_authors:"Author A"` rather than `publication_authors:Author A`. Until we support quoted phrases, search results will improve but it will only be filtering based off of last name instead of last name plus first initial.

**Comment by arielsvn** [comment]
moved to the frontend https://github.com/AlexsLemonade/refinebio-frontend/issues/719
