### ISSUE TITLE
Compendia page not returning download url field

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#1289]
### Context

Some endpoints that return an S3 download link require api consumers to send a valid token in the request headers. https://github.com/AlexsLemonade/refinebio-frontend/issues/560

### Problem or idea

The compendia endpoint (`/compendia`) detects the token, but it doesn't return anything in the `download_url`.

### Solution or next step

Tagging @kurtwheeler for input.

**Comment by arielsvn** [comment]
Seems like the reason why this isn't working is that `s3_bucket` and `s3_key` are `null` for the compendia we have. Maybe we should re-generate it?

**Comment by kurtwheeler** [comment]
You're right, the `s3_bucket` and `s3_key` are null for the compendium. This is because we don't set them once we upload them... which is a bug. Compendia take a while to generate and there's only one of them so I will do a bad thing and modify the one directly in the database, and create a fix so that this doesn't happen for new compendia we create.

**Comment by arielsvn** [comment]
Working now

![image](https://user-images.githubusercontent.com/1882507/57331166-f6af0e00-70e5-11e9-9911-dc31bafb67da.png)
