### ISSUE TITLE
Use MetaSRA metadata when available. 

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#1333]
### Context
Came up in my discussion with @cgreene yesterday.

### Problem or idea

There is metadata available on MetaSRA for some experiments on refine.bio. We can use that instead of the refine.bio's harmonized metadata. 

For experiments which aren't on MetaSRA, we can use refine.bio's harmonization.

The coverage would be for human data for now. 

### Solution or next step

Tagging @kurtwheeler for input on how much effort this would be and then see if we can include it in BetaBlockers.

**Comment by jaclyn-taroni** [comment]
Just to note: we generally do not have metadata for the RNA-seq data that is covered by MetaSRA #542

**Comment by kurtwheeler** [comment]
Hmm, I'm going to start thinking about/looking into how much effort this would be. However my initial thoughts are:
  * What's the justification behind including this in BetaBlockers? It doesn't really seem worth delaying our launch over. We might have the bandwidth to get it done before we hit a million samples, but it seems more like a nice-to-have than a reason to delay the widespread dissemination of our service.
  * Is there not a concern that having metadata from one source for some experiments and metadata from another source for others might make working with it hard? If they have different structures or field keys I would think that it'd be painful to work with two types of metadata, especially when there's not going to be an easy way to tell which experiment has which type of metadata. I might think a better option would be to include this metadata _in addition_ to refine.bio's harmonized metadata rather than _instead of_.

**Comment by jaclyn-taroni** [comment]
Having metadata for RNA-seq makes it considerably easier to work with when doing something like differential expression analysis, which we expect to be a major use case.

**Comment by jaclyn-taroni** [comment]
Note that that was not me saying _it needs to be in Beta Blockers_, but stating that as the most important reason I can think of.

**Comment by cgreene** [comment]
Our long-term plan should be to switch over to the metadata extracted via the MetaSRA approach. Their approach is more rigorous and granular than what we are doing. However, it covers only a modest fraction of samples.

One reason we might want to include this metadata instead of refine.bio's is that we expect that it should be better for the samples where it exists, and because it should - in the medium term - replace our metadata processing. I do think that we would need to prefix the fields with the metadata source (do we already do this for the refine.bio harmonized metadata?).

My inclination is that this is not a beta blocker issue, unless our metadata is so flawed for these samples that it prohibits or greatly impedes analysis. It sounds like we are not really getting metadata for these samples, so I think that strongly argues that this should not be a beta blocker.

**Comment by jaclyn-taroni** [comment]
> (do we already do this for the refine.bio harmonized metadata?)
Yes, with `refinebio_` prefix -- harmonized age is `refinebio_age`

**Comment by kurtwheeler** [comment]
Ok so my initial thoughts on how we can do this are:
  * We can pull metadata about an experiment from http://metasra.biostat.wisc.edu/api/v01/samples.json?study=SRP071643 (MetaSRA studies are equivalent to our experiments)
  * We can modify the SRA surveyor to do this when it surveys new experiments.
  * We can create a data migration to do this for existing experiments.

The part that still seems a bit tricky and unclear to me is how we're going to handle keeping up with MetaSRA as they add more metadata.

**Comment by cgreene** [comment]
I think @kurtwheeler lays out a good approach. Since we expect MetaSRA to be updated relatively infrequently, though, I have a few minor changes, and will chat with @wvauclain about this issue:

* Bulk download from http://metasra.biostat.wisc.edu/download.html
* Write management command to load metadata prefixed by MetaSRA_<VERSION>_Key
* Write logic to allow newer version fields to replace old ones if the value has changed (as opposed to preserving both values). Otherwise, prefer the oldest value. This assumes the new values are more correct.

**Comment by cgreene** [comment]
@wvauclain noticed that samples sometimes disappear. We asked the MetaSRA developers how we should consider their annotations:

> We were just looking at the MetaSRA downloads page. We've been trying to nail down what happens with new versions (can annotations be added/removed, only added, or something else).
> 
> It looks like the values for existing samples don't get changed.
> 
> However, we noticed something interesting. This id ( https://www.ncbi.nlm.nih.gov/sra/?term=SRS355591 ) appears in 1.0 to 1.4, and then it disappears in 1.5:
> Caseys-MacBook-Pro-2:Downloads cgreene$ grep SRS355591 metasra.v1-*
> metasra.v1-0.json:    "SRS355591": {
> metasra.v1-1.json:    "SRS355591": {
> metasra.v1-2.json:    "SRS355591": {
> metasra.v1-3.json:    "SRS355591": {
> metasra.v1-4.json:    "SRS355591": {
> Caseys-MacBook-Pro-2:Downloads cgreene$
> 
> Can you help us understand how we should think about these versions? Are these re-runs of the original rules to make annotations, updates with new rules, or something else?
> 

We got back a couple of replies, but the ones that really matter for us are:

> sometimes the accessions 
> disappear, but that does not appear to be the case here. Indeed this 
> sample should be in the newest version of the MetaSRA, but is not 
> included due to a processing error. We parallelize the processing of 
> samples in small batches and, looking at the logs, it looks like this 
> batch failed and I did not catch the failure.  I will look into this and 
> try to fix what happened. The next version of the MetaSRA should contain 
> this sample.  In light of this error, one way forward until the new 
> version would be to take the union of samples in all versions and to use 
> the annotations provided by the latest version.  The one caveat is that 
> there are a number of samples that are simply removed from the SRA from 
> version to version and so this process would result in some removed samples.
> 
> In general, the versions of the MetaSRA are executions of ~both~ new 
> rules ~and~ the new samples present in the latest version of the SRAdb. 
> Thus, it is possible for both the samples and ontology terms to change 
> from version to version.

For now, I think @wvauclain is going to try to tackle #542 and will shift back to this after some additional discussion and design input. We need to think more about how we want to integrate these annotations into our records and return them to the user because of how the annotations are structured. It will hopefully also help then that there may be an updated release.

**Comment by wvauclain** [comment]
Since we want to store the metaSRA metadata separately from the refine.bio metadata, we are going to need to modify the Sample model. Currently it stores harmonized metadata in fields like "age", etc. then converts those fields to "refinebio_age", etc. during serialization. If we are looking at storing both our harmonized metadata and the metaSRA metadata, it doesn't really make sense to have a field labelled "age" if it is one of the two fields that potentially has age metadata.

We might want to change the Sample model to using the fields "refinebio_age" and "metasra_age" (or something similar), which would require a migration. The upside of this approach is that the same metadata could update the names of the fields on the models and populate them with metaSRA data.

However, we may want to use a management command to periodically update our metaSRA metadata, since "it is possible for both the samples and ontology terms to change
from version to version".

Also, metaSRA stores all its metadata using ontology terms, so we will have to decide what way we want to go about converting those to words. The two possible methods that I see are using an ontology term API (like https://www.ebi.ac.uk/ols/docs/developer), or somehow downloading/creating a database of ontology terms that we can query. The local database would definitely save us on bandwidth and network requests per sample, so if it seems feasible it is probably the better approach.

**Comment by cgreene** [comment]
It may make sense to separate our metadata processing/request code from our surveying code. In the long term, we are working with the MetaSRA folks to expand what they can process to cover all of what refine.bio can ingest.

In preparation for when we do that, we may also want to move away from fields on the model as the primary means to store metadata (in part because we don't know what we'll get).

My suggestion at this point is that we push ahead #1350 and close the corresponding #542. Have a data migration clean up the metadata for the samples that were affected by the bug that got closed there. Then defer additional work on this issue until after everything preventing us from launching is addressed. This feels like a big increase in scope late in the game.

**Comment by wvauclain** [comment]
I spoke with @kurtwheeler, and it seems like the best way of dealing with ontology terms is similar to how we deal with organisms. I'm going to make an ontology term Model that stores the mapping between ontology terms and human-readable names.

When we call the function that gets the human-readable string from an ontology term, it will search the database for a cached ontology term. If it finds one, it will return that cached name, otherwise it will hit the OLS API to get the name.

To pre-populate the database with terms so that we do not overload the OLS server when importing all of the metaSRA data for the first time, we will have an alternate method of creating `OntologyTerm`s where we download the current entire ontology from OLS and parse it in one go.

To figure out which ontologies are necessary to download ahead of time, I ran this command to find all of the ontologies currently referenced in metaSRA:

```sh
grep -Eo '"\w*:\w*"' metasra.v1-5.json | tr -d '"' | awk -F ":" '{ print $1 }' | sort | uniq
```

It looks like we will have to download these ontologies before scraping metaSRA:

```
CL
CVCL
DOID
EFO
UBERON
UO
```

**Comment by kurtwheeler** [comment]
@dvenprasad This issue has all the backend code changes completed, barring some XML parsing issues that are probably due to code rot/API changes. But I don't think the frontend supports it at all, so we'll still need to implement some things there.

**Comment by davidsmejia** [comment]
Closing
