### ISSUE TITLE
Nomad Workaround - EBI ENA fallback to NCBI SRA

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#1441]
### Context

We have tried named pipes and Nomad's tempfs solutions to deal with unmated read data.

### Problem or idea

We still have difficulty dealing with unmated read data. EBI's ENA is slower and somewhat less reliable for us, especially at scale, than NCBI's SRA for downloading. However, EBI provides fastq files, so we can download only the paired reads.

### Solution or next step

We could survey via ENA. If there are unmated reads, we download fastq files from ENA. If there are not unmated reads, we download via NCBI's SRA and use the named pipes solution.

**Comment by kurtwheeler** [comment]
@wvauclain's work on finding a solution involving a buffer has hit the same `container exited wtih status code 137` that we saw when running salmon using tmpfs before. He's digging into where that's coming from using some suggestions from https://github.com/hashicorp/nomad/issues/6060#issuecomment-517738777.

However that's a rather difficult error to debug and he may or may not be able to figure out why it's happening. Therefore I'm going to begin implementing this now and we'll see who gets something working first. I think this issue is worth potential duplication of effort given it's critical and blocking nature.
