### ISSUE TITLE
Record annotation version for Transcriptome Indices

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#163]
### Context

In https://github.com/AlexsLemonade/refinebio/pull/162 I have made the versions of these genome annotations explicit by making them constants. However 

### Problem or idea

As per the discussion on the aforementioned PR we will want to make these displayable "at a glance", which will require adding an annotation to the computational results for these.

### Solution or next step

We should add a CompultationalResultAnnotation to Transcriptome Indices which specifies which genome annotation version was used to compute it.

**Comment by Miserlou** [comment]
CompultationalResultAnnotation may not be the best way to store this information. Deepa has been developing this notion of "pipeline", and this at-a-glance information may want to be part of that. I still have some outstanding TODOs in my personal notes that shook out from that DB meeting last week that I haven't gotten to yet because of all this devops work.

**Comment by jaclyn-taroni** [comment]
Was this closed by #318?

**Comment by kurtwheeler** [comment]
This was addressed by #310 because now `OrganismIndex` has a `source_version` column which corresponds to the assembly version from Ensembl we used.

**Comment by cgreene** [comment]
Just chatted with @kurtwheeler and this currently grabs the Ensembl version but also needs to store the genome information (e.g., `GRCh38.p12`) in a way that we can easily return it to the user.

**Comment by kurtwheeler** [comment]
Closed by #456
