### ISSUE TITLE
Humanize Pipeline Names

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#170]
Currently "pipelines" are represented internally as long UNIX commands or as R functions.

When we display this information, we'll want to have descriptive, intuitive, human-friendly ways of representing this information..

I'm guessing we'll probably need a Pipeline table just to house name and description information for each of our pipelines.

**Comment by Miserlou** [comment]
From @jaclyn-taroni:

```
Salmon is an alignment-free method for estimating transcript abundances from RNA-seq data. We use it in quasi-mapping mode, which is significantly faster than alignment-based approaches and requires us to build a Salmon transcriptome index. We build a custom reference transcriptome (using RSEM rsem-prepare-reference) by filtering the Ensembl genomic DNA assembly to remove pseudogenes, which we expect could negatively impact the quantification of protein-coding genes. This means we're obtaining abundance estimates for coding as well as non-coding transcripts. We include the flags `--seqBias` to correct for random hexamer priming and, if this is a paired-end experiment, `--gcBias` to correct for GC content when running `salmon quant`.
```

```
SCAN (Single Channel Array Normalization) is a normalization method for single channel (Affymetrix) microarrays that allows us to process individual samples. SCAN models and corrects for the effect of technical bias, such as GC content, using a mixture-modeling approach. For more information about this approach, see the primary publication (Piccolo, et al. Genomics. 2012. DOI: 10.1016/j.ygeno.2012.08.003) and the SCAN.UPC bioconductor package documentation (DOI: 10.18129/B9.bioc.SCAN.UPC).
```

**Comment by Miserlou** [comment]
Rich [3:32 PM]
Does “Abundance Estimation” and “Array Normalized” make sense

jaclyn.taroni [3:38 PM]
RNA-seq abundance estimation makes sense
and you can probably just say Single Channel Array Normalized

**Comment by Miserlou** [comment]
We need on for "NO-OP"

**Comment by jaclyn-taroni** [comment]
"Submitter-processed" ?

**Comment by Miserlou** [comment]
That's what I was thinking, but it seems vague to the point of usefulness. Can we do better than "processed"?

**Comment by jaclyn-taroni** [comment]
Well, it will likely be processed in multiple (not-entirely-standardized) ways and the field on GEO that tells us that is `data processing`. So unless we normalize that information (which may be possible), I don't know how we would get more specific.

**Comment by kurtwheeler** [comment]
@jaclyn-taroni can you provide a human readable name for each pipeline we have?

**Comment by jaclyn-taroni** [comment]
Here are the "read more" links for Salmon: 

* Website (includes "Getting Started" which some users may be interested in): https://combine-lab.github.io/salmon/
* Documentation: https://salmon.readthedocs.io/en/latest/
* Publication: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5600148/ (closed access at _Nature Methods._)
* Github: https://github.com/COMBINE-lab/salmon

We might not want to use every single one of these, so should discuss options.

**Comment by jaclyn-taroni** [comment]
Here's a draft of the tximport copy:

`tximport` imports transcript (tx)-level abundance estimates generated by `salmon quant` and summarizes them to the gene-level. We use the tx to gene mapping generated as part of our reference transcriptome processing pipeline. Our tximport implementation generates ["lengthScaledTPM"](https://www.rdocumentation.org/packages/tximport/versions/1.0.3/topics/tximport), which are gene-level counts that are scaled using the average transcript length across samples and to the library size. Note that tximport is applied at the _experiment-level_ rather than to single samples. For additional information, see the [tximport Bioconductor page](http://bioconductor.org/packages/release/bioc/html/tximport.html), the [tximport tutorial _Importing transcript abundance datasets with tximport_](http://bioconductor.org/packages/release/bioc/vignettes/tximport/inst/doc/tximport.html), and [Soneson, et al. _F1000Research._ 2015.](http://dx.doi.org/10.12688/f1000research.7563.1)

**Comment by jaclyn-taroni** [comment]
Looks like @dvenprasad has all the copy she needs for Keytar Kurt, so I will close this.
