### ISSUE TITLE
Create copy for landing page.

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#183]
### Problem or idea

The refine.bio landing page needs copy to help users contextualize what refine.bio is and what they can do with refine.bio. 
The copy should cover:
- Type of data available
- Should orient user to availability of different pipelines
- Expected end result (i.e what type of files do they get) 

### Solution or next step
Deepa will write up a draft of the copy.

**Comment by cgreene** [comment]
I might leave out the "adult and pediatric cancer" part at this stage. We don't want to lose the zebrafish people, for instance, who study these diseases are tired of hearing about uniform datasets that don't contain what they need.

I think we should present it as harmonized data in the resource itself. The use cases that we show should be childhood cancer specific.

I also think it's good to have the childhood cancer specific landing page before things launch to make clear the reasons for why we're putting this together.

**Comment by kurtwheeler** [comment]
> Search the collection uniformly processed RNA-seq and microarray data from adult and pediatric cancers sourced from publicly available data sources like GEO, ArrayExpress, and SRA.

Should be:

> Search the collection OF uniformly processed....

**Comment by dvenprasad** [comment]
**Copy above the  search bar (quickly explaining what is the data they are searching through)** 

Search for harmonized transcriptome data from publicly available sources

**Below the search bar (Providing more details and other things they can do.)**

- Search the collection harmonized RNA-seq and microarray data from publicly available sources like GEO, ArrayExpress, and SRA. The data has been processed with a set of standardized pipelines (link to doc) curated by the CCDL <link> 

- Build custom datasets tailored to your needs. 

- Download 
   - Gene expression matrices
   - Sample metadata
   - Quality reports

**Comment by kurtwheeler** [comment]
> Search the collection harmonized RNA-seq

Is still missing an `of` between `collection` and `harmonized`.

**Comment by dvenprasad** [comment]
Yes, it was. It's corrected now. Thanks.

**Comment by kurtwheeler** [comment]
This came up during tech team meeting as being ready for a look by @cgreene and/or @jaclyn-taroni

**Comment by cgreene** [comment]
The second version from @dvenprasad seems good to me. Is "CCDL" a link? Most people won't know who that is. Also, could we have 2 bullet points:

* Search the collection of harmonized RNA-seq and microarray data from publicly available sources like GEO, ArrayExpress, and SRA. The data has been processed with a set of standardized pipelines (link to doc) curated by the CCDL.
* Build and download custom datasets tailored to your needs including gene expression matrices and sample metadata.

I left out the QC reports since those will only come from RNA-seq data initially and they are more "along for the ride" than "primary data people want to find"

**Comment by dvenprasad** [comment]
@cgreene  Yes, CCDL can be a link and I think it should be Childhood Cancer Data Lab (CCDL) instead of just CCDL.

The two bullets sound good to me.
