### ISSUE TITLE
Record which samples end up making it into a compendia

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1838]
### Context

As we build compendia we drop some samples that aren't suitable for various reasons. However the only record in our database that tracks what samples are in it is the dataset object which has every sample including those that get dropped.

### Problem or idea

We should track this... _somehow_

### Solution or next step

We should already have this information in the compendia's data because during the first pass over the samples we keep track of the gene ids, the microarray samples, and the rnaseq samples. It's just a matter of actually getting this into the database.

**Comment by cgreene** [comment]
If we want this to be for users of the compendium but not the front end we could include one or more files that list the samples dropped and the stage at which they were dropped.

**Comment by kurtwheeler** [comment]
> If we want this to be for users of the compendium but not the front end we could include one or more files that list the samples dropped and the stage at which they were dropped.

Ooooh I like that! We should do that! That'll require keeping track of what samples we drop at each step that can drop samples.

But also, we should look at the matrix we create rather than the dataset in places like 
https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/smashing_utils.py#L884-L899 and https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/smashing_utils.py#L661-L666

**Comment by arielsvn** [comment]
I went over the code and found 4 places where we drop samples, @kurtwheeler let me know if I'm missing any:

- on `_prepare_input` we drop any samples without a smashable file or if we have an error downloading the file from S3

- on `_prepare_frames` we do two passes over all `computed_files, samples` and drop all the samples where we can't load the data from the computed file.

- on `_perform_imputation` we drop all the samples "with <50% present values"

Do we want to include the samples that are dropped on all of these steps? The ones that are dropped in the imputation step seem more important.

Also, since we have multiple reasons why samples can be dropped, how should we write this information into the metadata. Instead of using separate files I'm thinking we could also add an additional property to the metadata on the sample details.

**Comment by arielsvn** [comment]
I discussed this with @kurtwheeler and we came up with several options:

1. Only include the samples that made into the compendia in `aggregated_metadata.json`, and then have a different file (eg `missing_samples_metadata.json`) with the samples that didn't make it and the reason why. Something like:
    ```
    {
    "GSM1232": {
        "reason": "We failed while downloading the computed file",
    },
    "sample_accession_code": {
        "reason": "Sample had <50% present values"
    },
    [...]
    }
    ```
    We could also add all sample metadata there, and the experiment relations.

2. We can include **all** samples in `aggregated_metadata.json` and still keep a different file with the reasons why they didn't make it into the compendia (eg `missing_samples_metadata.json`)

3. We can include two new fields for each sample in the current `aggregated_metadata.json`: a boolean value specifying whether the sample is in the compendia, and a `reason` for the ones that didn't make it.

Which one do you think is better? @jaclyn-taroni @cgreene

**Comment by cgreene** [comment]
I like Option 1 with the term "filtered" instead of "missing", I think.

**Comment by jaclyn-taroni** [comment]
Agree with @cgreene
