### ISSUE TITLE
We are not caching the first pass on the compendia

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#1865]
### Context

Creating the compendia takes a long time, and we try to cache some information between runs.

### Problem or idea

Looks like this isn't working, I looked into the human compendia folder that we are running now.

Also, we save the cache into `job_context['work_dir']`

https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/smashing_utils.py#L299

This directory get's removed every time the job starts. 

https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/smashing_utils.py#L109-L111

### Solution or next step

I think we should store the cache outside of `work_dir`, and change the time to associate it with the compendia organism.

**Comment by kurtwheeler** [comment]
> I think we should store the cache outside of `work_dir`
We are. The cache isn't in this dir: https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/smashing_utils.py#L109-L111, because we create a different work_dir for compendia jobs: https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/create_compendia.py#L66. That code is called after `prepare_files`, so the "work_dir" we remove is `job_context["work_dir"] = "/home/user/data_store/smashed/" + dataset_id + "/"` not `job_context["work_dir"] = SMASHING_DIR + job_context["organism_name"] + "/"`, which is where we store the cache.

I will admit this is a confusing way of dealing with the `work_dir`, but I was trying to make some changes so that only the compendia code would have special logic for it. Maybe that wasn't the best idea because now this is getting confusing.

Finally, we changed file permissions to prevent the job from being able to remove the cache files we didn't want getting cleaned up. It blows my mind that those files are somehow missing, nothing without root access should have been able to remove them.

I will dig into this issue further but I think that the original diagnosis is off.

**Comment by kurtwheeler** [comment]
This is working correctly:
```
2019-11-04 23:09:38,663 i-0119de425230c426b [volume: -1] data_refinery_workers.processors.smashing_utils INFO [job_id: 29353126]: The data from the first pass was cached, so we're using that and skipping the first pass.
2019-11-04 23:09:38,666 i-0119de425230c426b [volume: -1] data_refinery_workers.processors.smashing_utils DEBUG [total_cpu: 0.7] [process_ram: 6.429279327392578] [job_id: 29353126]: Beginning to build the full matrices.
2019-11-04 23:46:43,028 i-0119de425230c426b [volume: -1] data_refinery_workers.processors.smashing_utils DEBUG [total_cpu: 0.8] [process_ram: 1019.5162353515625] [job_id: 29353126]: processing frame 0
```
