### ISSUE TITLE
Compendium Identifiers -> Start with "approved" set

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#1882]
### Context

We currently have 10 times as many human (and maybe other organism) gene identifiers as we could plausibly include in the compendium. This is because our no-op processors seem to be occasionally leaking through data that is not identifier remapped.

### Problem or idea

We should restrict our compendium-building procedure to a set of genes that we could plausibly include. This will help to avoid blowing up our memory requirements as we're putting the compendium together.

One idea -> filter each incoming sample to only genes that are in our RNA-seq set. It seems unlikely that we would be able to have enough measurements for things that are not found in RNA-seq.

Another idea (probably more flexible/preferable) -> Since we're now doing two passes over the data, in the first pass don't create a set of all identifiers. Instead, create a dictionary. The keys would be the identifiers. The values would be number of samples in which that key was observed. We'd also store the number of samples processed.

Then, after the first pass we'd only retain those identifiers that are in >= 50% of the samples. This should leave somewhat more identifiers than we remove here:
https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/create_compendia.py#L230
because it both filters to a lower threshold and also because we drop certain genes from the RNA-seq step if they are very lowly expressed:
https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/create_compendia.py#L170

If we're going to stick with two-pass, I think the second approach is better. It's more flexible for cases where the transcriptome indices don't yet exist. For example, those currently referenced in https://github.com/AlexsLemonade/refinebio/issues/1722.

### Solution or next step

@jaclyn-taroni @kurtwheeler curious as to your thoughts.

**Comment by kurtwheeler** [comment]
Ok so the only question I have about this solution is what to do about samples that have the wrong gene ids. Specifically in terms of deciding when to drop the samples entirely.

Here's the method for dropping these that I've come up with so far:
  - Instead of the dictionary having its values be the number of samples with the gene id, instead build a list of the samples that have the gene id.
  - Then once that dict is built we can count the number of samples for each gene id, and filter out the gene id if that count isn't 50% of total samples.
  - Then we can just use every sample that is still in the dict for the full matrix (with a set union across all the gene ids' samples.)


How does that sound? I think I could see this solution having an issue with leaving samples that have only a few gene ids that make the cutoff so then most of their values end up being null. Should we do another cutoff where if a sample is missing X% of gene ids we filter it out? What would X be?

What are your thoughts @cgreene @jaclyn-taroni ?

**Comment by cgreene** [comment]
Those samples are already dropped in line 246, so I don't think we need to filter the list of samples in an additional way:
https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/create_compendia.py#L246

Anything where all of it's identifiers are dropped should have >50% missing.

**Comment by kurtwheeler** [comment]
Ah ok, I thought we might have been doing that but when I went looking for it I instead found https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/create_compendia.py#L165, forgetting we filter samples twice.

I will point out that the filtering you linked happens _after_ what I linked. It seems like having samples with a horrible but non-disjoint gene-id-set would cause this calculation to be off: https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/create_compendia.py#L161. Do you think that's a concern?

**Comment by cgreene** [comment]
I think that 161 is dropping genes and not samples. I also don't think anything that happens in 161 will apply to these samples, since all of the RNA-seq data is processed from raw data (I think?) and should have sensible identifiers.

**Comment by cgreene** [comment]
We also drop all genes with fewer than 70% of values in the combined matrix in 230:
https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/create_compendia.py#L230

This should be more stringent than what I proposed above with the 50% threshold (which was just to get us to a manageable size).

**Comment by kurtwheeler** [comment]
> We also drop all genes with fewer than 70% of values in the combined matrix in 230

Righto, I think that gene filtering stuff will be fine.

> I think that 161 is dropping genes and not samples.

Also righto, I got that mixed up. However, while 
> all of the RNA-seq data is processed from raw data

is true,

> should have sensible identifiers

is not as much of a given because we preallocate both microarray and rna-seq matrices with the same set of gene identifiers so we don't have to rearrange them when we go to combine them.

**Comment by cgreene** [comment]
Ahh - true! But with the filtering of genes at the loading stage based on counts, it should at least be more sensible than it is now.

Actually, I wonder if that preallocation is breaking line 161 right now. In the past, genes would have to have at least had a count to show up there. Now, not so much, right?

**Comment by kurtwheeler** [comment]
Yeah line 161 might be pretty broken because there could be some microarray-only gene ids in there that have nothing in the RNA-Seq matrix. This change will probably make this better, but only maybe will actually fix it. (The only way this change fixes it if 

>  It seems unlikely that we would be able to have enough measurements for things that are not found in RNA-seq.

is strictly true).

Do you think this is something we need to fix in a more robust way?

**Comment by cgreene** [comment]
I expect that @jaclyn-taroni added that step to avoid having a ton of zeros from RNA-seq mess up the quantile normalization step. If there are many things that would never have been assayed on our QN target platform, we'd have trouble dealing with them.

In the medium-term I think we are probably due for a reevaluation of how we perform quantile normalization on the compendia, but this requires us to get compendia together first.

For now, we could recapitulate the prior behavior by adding a line to drop any genes in the RNA-seq matrix that are entirely missing right before we do that 10% drop. This shouldn't be a terribly large computational efficiency hit, and I'd imagine that preallocation time savings, if it reduces the number of malloc steps, would more than make up for it.

**Comment by kurtwheeler** [comment]
> For now, we could recapitulate the prior behavior by adding a line to drop any genes in the RNA-seq matrix that are entirely missing right before we do that 10% drop.

Awesome, sounds like a plan to me!

**Comment by cgreene** [comment]
The underlying issue was fixed by #1889
