### ISSUE TITLE
Easier programmatic access to single datasets

### ISSUE THREAD

**Issue by seandavi** [AlexsLemonade/refinebio#1980]
### Context

In the webapp, multiple steps (add dataset, go to dataset page, download) are required to download a single experiment worth of data. These steps are (I think) not available programmatically. 

### Problem or idea

Since a common use case is to grab a single study for analysis, would it be possible to make a simple API call or download link (+/- transformations) per experiment? Perhaps I have missed something in the docs, though, that would allow this?

### Solution or next step

In a sense, I am proposing a (set of) API endpoints that are experiment-focused. Having something like this in place would facilitate building a quick-and-dirty access method from R/Bioconductor.

**Comment by cgreene** [comment]
Hi @seandavi : thanks for this suggestion! I think the path to doing this at the moment is multi-step:
* Use experiments endpoint to get the experiment.
* Get the associated samples' accession codes.
* Use those accession codes on the dataset_create endpoint.
* Use dataset_update to set options.

Since that use case is pretty common, we may also want to support it on the frontend as well.

**Comment by seandavi** [comment]
Thanks. We can work with your outlined approach for now. If I get a moment, I'll try to update your docs with that workflow (though it may be there already somewhere).

**Comment by cgreene** [comment]
Hi @seandavi : I'm going to consider this, at the moment, a documentation issue where we will provide documentation for the API about how to do this along with example code. I've also created https://github.com/AlexsLemonade/refinebio-frontend/issues/810 to track design towards a button on the frontend that could enable this for non-API users.

**Comment by dvenprasad** [comment]
I think we should make the endpoint so users can download datasets using experiment accession code and provide transformation and QN options.

**Comment by mbernste** [comment]
Hi @cgreene, the functionality requested here is very similar to that which we need to allow users to download refine.bio expression matrices directly from the MetaSRA website's search-results. 

So far, it looks like the dataset_create endpoint is what we need. However, it took me a little bit to figure out how to find the dataset's webpage using it's uid.  That is, it is simply https://www.refine.bio/dataset/<dataset_id>

I think some documentation or a tutorial that explains how to pragmatically go from a set of arbitrary sample accessions to the URL of the dataset's webpage would be quite useful.  It would be great if this tutorial walked through a specific sequence of API calls.

My apologies if this information is in the documentation and I simply missed it!

**Comment by arielsvn** [comment]
@mbernste thanks! we need to work on improving our API documentation, and also adding some tutorial as you suggested. We are currently working on an API client that should help users search and download data from the website.

In the meantime, I created some helper functions to build datasets from a set of experiment accession codes or by specifying the samples you want in them. https://repl.it/@arielsvn/refinebio-api

With them you should be able to do:

```py
import refinebio
token_id = refinebio.create_token()
experiment_sample_data = {
  'GSE24528': ['GSM604799', 'GSM604797'],
  'GSE9091': ['GSM230302', 'GSM230295']
}
dataset_url = refinebio.create_dataset(experiment_sample_data, token_id)
```

In order to get the URL associated with a refinebio's dataset. Hope this helps.

**Comment by mbernste** [comment]
Thank you! This is very helpful

**Comment by arielsvn** [comment]
Of course, feel free to use these. Even after we release a Python client for easier access these Web Apis are unlikely to change.

To answer the original issue, a single experiment could be downloaded using [the helpers above](https://repl.it/@arielsvn/refinebio-api) with:

```py
import refinebio
data = refinebio.get_experiment_samples(['GSE24528'])
dataset_url = refinebio.create_dataset(data, scale_by='MINMAX')
```

**Comment by kurtwheeler** [comment]
We have a python client for this! Documentation can be found at https://alexslemonade.github.io/refinebio-py/index.html

Specifically for downloading datasets we have a [function which makes it easy](https://alexslemonade.github.io/refinebio-py/quickstart.html#downloading-datasets).
