### ISSUE TITLE
Unexpected gene ids for RNA-seq data

### ISSUE THREAD

**Issue by ajlee21** [AlexsLemonade/refinebio#2142]
### Context

I recently downloaded Pseudomonas aeruginosa experiments using search parameters:
Searched for "Pseudomonas"
Organism = Pseudomonas aeruginosa
Technology = RNA-seq (991)
Experiment = ERP006680

When opened the expression .tsv file I got a matrix that I assume was gene id x sample id

Here is a snippet of the matrix I am looking at for reference:
```
Gene | ERR583484 | ERR583485 | ERR583486 | ERR583487 | ERR583488
PAERUG_P64_East_of_England_6_01_14_00001 | -0.068451652741766 | -0.187662618022796 | -0.050419056574555 | -0.046354567071277 | -0.07222994283495
PAERUG_P64_East_of_England_6_01_14_00002 | -0.170895815010441 | -0.187662618022796 | -0.194288940281942 | -0.195375379056711 | -0.181418409672225
PAERUG_P64_East_of_England_6_01_14_00003 | 0.337920004373081 | 0.366724562898171 | 0.402170323465722 | 0.355972724112278 | 0.414538879839071
PAERUG_P64_East_of_England_6_01_14_00004 | 0.604919551575815 | 0.482704175110198 | 0.638381137330624 | 0.839785650864304 | 0.65961801509901
```
The gene id's were of the form ```PAERUG_P64_East_of_England_6_01_14_00001```  which I did not expect.  I had expected ids of the form "PA0001" or "PA14_####"

### Problem or idea

I guess I am unsure where these IDs are from?  

### Solution or next step

And I wonder if it would be possible to get the database that these IDs are from so that I could map them to IDs that I can use to plug into this tool: https://bactome.helmholtz-hzi.de/cgi-bin/h-pange.cgi

**Comment by kurtwheeler** [comment]
Alright so it looks like we used the wrong assembly.

What I think happened is that Fungi have a strange identifier in their species names, so I wasn't able to do an exact match on species names. However this meant that I matched on pseudomonas_aeruginosa_gca_001181945 instead of pseudomonas_aeruginosa. We didn't have a strain mapping for pseudomonas_aeruginosa_gca_001181945, only pseudomonas_aeruginosa. Therefore our strain mapping was ignored and we used the wrong geneset for that organism.

Basically ensembl has a lot of edge cases and to use their APIs we have to do a lot of convoluted things like this: https://lists.ensembl.org/pipermail/dev_ensembl.org/2019-December/013614.html

I think that this might not be too involved of a fix. I just tested changing the test for species name to `organism_name == species["name"]` instead of `organism_name in species["name"]` and it looks like it found the correct species and assembly. This isn't quite robust enough of a solution, because  this will break the Fungi division, but a few more overly specific `if` statements ought to do it.

The resolution for this issue is then:
  * Make a PR with the improved special handling of edge cases.
  * Deploy that
  * Determine if other species were also affected by this issue
  * Unsurvey all the affected organisms.
  * Rebuild transcriptome indices using the improved code.
  * Rerun all the affected organisms.

@cgreene do you want me to prioritize this for this sprint?

**Comment by cgreene** [comment]
I think that we should not be distributing data with the wrong identifiers relative to our documentation. We should either make those samples quickly not downloadable while we develop a fix and continue on the sprint as planned, or we should get this fixed and these organisms re-run. If you do the latter, move something of roughly equivalent weight off the sprint.

**Comment by kurtwheeler** [comment]
Hi @ajlee21! This issue should be resolved now! I rerun all the Pseudomonas aeruginosa with the correct assembly. I downloaded an experiment and it's got the PAXXX gene identifiers you were hoping for. Additionally I've created a compendia for that organism so if you just want all of our normalized data for it you can download it all easily here: https://www.refine.bio/compendia#normalized
