### ISSUE TITLE
Replace all usages of `urllib.request.urlopen` with `requests`

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#2224]
### Context

https://github.com/AlexsLemonade/refinebio/pull/2223#pullrequestreview-390887303

### Problem or idea

Looks like `urllib.request.urlopen` doesn't stream the data when downloading from an URL. This probably caused some jobs to be OOM-Killed.

We should use [requests](https://stackoverflow.com/a/39217788/763705) and replace all usages of `urllib.request.urlopen` with:

```
with requests.get(download_url, stream=True) as r:
    with open(target_file_path, "wb") as f:
        shutil.copyfileobj(r.raw, f)
```

### Solution or next step

Replace all usages of `urllib.request.urlopen` with `requests`

**Comment by wvauclain** [comment]
I looked into this more, and it looks like we can't really replace `urllib.request.urlopen` with `requests` anywhere else, because `requests` does not support FTP.

I did some testing locally though, and `urllib.request.urlopen` does stream data when downloading from a URL, just maybe not quite as fast as `requests`, so I am not sure where the OOM errors were coming from.

**Comment by kurtwheeler** [comment]
Okay great then. It sounds like there's not really much more to be done. We may want to look into OOM errors at some point, but I think that will only come up if/when we prioritize that job error type. (I imagine we'll either prioritize job errors to debug based on how many jobs they affected or which experiments they affected)
