### ISSUE TITLE
It's not possible to run a dev stack outside `us-east-1`

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#2240]
### Context

I was testing an infrastructure change with a dev-stack deployed on `us-east-2`

### Problem or idea

Looks like some scripts are dependant on the region, and they assume that the app is deployed on `us-east-1`. For example: https://github.com/AlexsLemonade/refinebio/blob/dev/infrastructure/nomad-configuration/client-instance-user-data.tpl.sh#L31-L35

When looking into one of the instances I got the following error:

```
+ EBS_VOLUME_ID=null
+ aws ec2 attach-volume --volume-id null --instance-id i-00162d77206f82d6a --device /dev/sdf --region us-east-2

An error occurred (InvalidParameterValue) when calling the AttachVolume operation: Value (null) for parameter volume is invalid. Expected: 'vol-...'.
```

### Solution or next step

Find the places where `us-east-1` is used and replace it with the region variable.

**Comment by wvauclain** [comment]
If we want to run outside `us-east-1`, we also might have to find a different AMI for the new region. We used to try to do this here:
https://github.com/AlexsLemonade/refinebio/blob/ed0988fedeb18adc74ff26cb4a0cbfbef0778ecd/infrastructure/instances.tf#L11
but since that other AMI doesn't have docker installed it wouldn't have worked anyway.

**Comment by kurtwheeler** [comment]
Closed by https://github.com/AlexsLemonade/refinebio/pull/2498
