### ISSUE TITLE
Transcriptome index redownloading end-to-end test race condition

### ISSUE THREAD

**Issue by wvauclain** [AlexsLemonade/refinebio#2321]
### Context

I uncovered a lot of bugs in our transcriptome index tests when trying to migrate to GitHub Actions.

### Problem or idea

It turns out that when we launch both transcriptome index jobs in our transcriptome redownloading test at the same time and your machine has enough ram to run them both at the same time, the downloader job is not recreated. The reason is, they both check if there are any other blocking tasks, and they both see each other, so they do not requeue the downloader job.

### Solution or next step

For now, I just made the tests run the two jobs in serial. But I am not sure what a permanent fix for this is, it's really tricky because of the concurrency.

**Comment by kurtwheeler** [comment]
Hmm, I'm thinking that one way to solve this long term may be to just remove redownloading cases from transcriptome index jobs. There aren't too many organisms so we can probably keep track of them pseudo-manually just fine, and if we ever need them to be started over we can just dispatch fresh transcriptome index jobs via surveyors since they won't be blocked by pre-existing objects.

**Comment by kurtwheeler** [comment]
I solved this race condition in https://github.com/AlexsLemonade/refinebio/commit/3fc64900a66971e74ed26cff5f70e7e9cd64e0ce by modifying the `OriginalFile.needs_processing()` method. I was running into this race condition in the new end to end tests and was able to resolve it.
