### ISSUE TITLE
Add a unit test for tximport

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#243]
### Context

Once `tximport` is implemented (#82), we'll need a unit test to ensure that we don't break this processor such that we get output that is dramatically different from what has been produced in the past.

### Problem or idea

There are a few challenges to keep in mind if this is part of an "end-to-end" test of the RNA-seq processing pipeline: 1) the genome version may change (at which point we probably need to update our test data)  2) the version of Salmon may change (which may affect either the preparation of the index or the quantification) and 3) `salmon quant` is nondeterministic. So, it will not be sufficient to run test data and compare the checksums.

We'll probably want something similar to what is done for the Affymetrix SCAN processor:
https://github.com/AlexsLemonade/refinebio/blob/60fdd5a4e2ed5a02ff466888914f4a5874ebfde5/workers/data_refinery_workers/processors/test_array_express.py#L206

And what Kurt mentioned [here](https://github.com/AlexsLemonade/refinebio/issues/117#issue-296499941).

Specifically, we'll want to make sure that the test data is highly correlated with the reference data.

### Solution or next step

To be revisited once #82 has been accomplished.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by dongbohu** [comment]
@jaclyn-taroni: Given a fixed set of `quant.sf` and the gene2txmap input files, how likely is the R package `tximport` (not our own wrapper script in `refinebio/workers/data_refinery_workers/processors/tximport.R`) going to generate different output files? I think this will only happen when `tximport` package changes its implementation. Since our Docker image of `salmon` pipeline will explicitly state the version number of `tximport`, I think we can just compare the checksums of the two output files with the expected output.

The issues you guys were talking about should be addressed by the unit tests of `salmon quant`, not `tximport`.

**Comment by jaclyn-taroni** [comment]
> That is more like an integrated test than a unit test.

Gotcha, good to know 👍

**Comment by dongbohu** [comment]
Done in PR #278.
