### ISSUE TITLE
GSE88884 is missing samples

### ISSUE THREAD

**Issue by wvauclain** [AlexsLemonade/refinebio#2432]
### Context

A user contacted us

### Problem or idea

On refine.bio, [GSE88884](https://www.refine.bio/experiments/GSE88884/gene-expression-changes-in-baseline-sle-patients-vs-healthy-controls-from-two-phase-iii-trials-illuminate-1-and-illuminate-2-of-b-cell-activating-factor-blockade-with-tabalumab) has 904 downloadable samples and 938 samples total, but on [GEO](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE88884) it has 1820 samples. 

### Solution or next step

Try surveying the sample locally and see how many samples we find. Either we have a surveyor bug, or we used to and we should re-run this experiment.

**Comment by wvauclain** [comment]
I ran the surveyor locally and it created 1820 samples. Looks like we should just have to re-survey the experiment on prod.

**Comment by cgreene** [comment]
https://www.refine.bio/experiments/GSE88884/gene-expression-changes-in-baseline-sle-patients-vs-healthy-controls-from-two-phase-iii-trials-illuminate-1-and-illuminate-2-of-b-cell-activating-factor-blockade-with-tabalumab

Has 1796 samples available. For some reason, 24 got missed. I'm guessing this is a filename -> sample name matching issue. Since these are from a clinical trial they should be among the best annotated. It's a bit of a surprise that they're not there.

**Comment by kurtwheeler** [comment]
The 24 were missed because there was an R issue which resulted in them getting set to no_retry=True a long time ago. I've gotten them to reprocess successfully and now the experiment has all 1820 samples available.

I also discovered that an additional 1744 samples can probably be fixed because of this: https://github.com/AlexsLemonade/refinebio/issues/2583

**Comment by jaclyn-taroni** [comment]
Did we contact the user yet?

**Comment by kurtwheeler** [comment]
Oops, that should probably happen before I close it! @cgreene they contacted you?

**Comment by cgreene** [comment]
Just replied 👍 🚀
