### ISSUE TITLE
How should the predicted metadata be included in the downloadable metadata files?

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#2872]
### Context

Discussing how MetaSRA and contributor predicted metadata should be provided to users on download.

### Problem or idea

We have the MetaSRA predicted metadata and will likely have predicted metadata from other contributors in the future. Along with the predicted values, there is also confidence information available.

- How should these be included in the download file?
    - Separate file?
    - Same metadata file, with fields suffixed?
    - something else???
    
- How should the confidence information be provided? (if it should be provided)

### Solution or next step

We can start by dogfooding this one. Tagging our resident scientists  for their opinions @cbethell @jashapiro @allyhawkins @jaclyn-taroni

**Comment by jaclyn-taroni** [comment]
Updated the title to be a little more informative. Here's the section of the docs on downloadable files for reference: http://docs.refine.bio/en/latest/main_text.html#downloadable-files

**Comment by jaclyn-taroni** [comment]
These answers should be considered a starting point.

> * How should these be included in the download file?
>   
>   * Separate file?
>   * Same metadata file, with fields suffixed?
>   * something else???

Of these, same metadata with fields suffixes strikes me as the way to go, i.e., use `predicted_` the same way we use `refinebio_`. I would also like to mention that we may want to include the source in the prefix, too, as that may help to orient users when they go to look at docs or a publication for example. So for MetaSRA, perhaps we could use `predicted_metasra_` or maybe the prefix relies _solely_ on source: `metasra_`. 

However, I expect _a lot_ of ontology terms to be included in MetaSRA data. So a question I have, because I do not remember off of the top of my head, is: Do we expect every ontology term supported by MetaSRA to be included for every sample?

_If so_, I might change my answer to separate file?

> 
> * How should the confidence information be provided? (if it should be provided)

I think that this is probably a question for the TSV file because that seems trickier to me than the JSON, where including it would likely be pretty straightforward (but tell me if I'm wrong!). What about something like `predicted_metasra_<term>.confidence`?

**Comment by wvauclain** [comment]
<details>
<summary>Here's an excerpt from the JSON file that we ingest from</summary>
```json
[
    {
        "sample_accession": "ERR2080620",
        "attributes": [
            {
                "EFO:0000721": {
                    "value": 6.0
                }
            }
        ]
    },
    {
        "sample_accession": "ERR3348231",
        "attributes": [
            {
                "EFO:0000246": {
                    "value": 3.0
                }
            }
        ]
    },
    {
        "sample_accession": "ERR3348230",
        "attributes": [
            {
                "EFO:0000246": {
                    "value": 3.0
                }
            }
        ]
    },
    {
        "sample_accession": "ERR3348229",
        "attributes": [
            {
                "EFO:0000246": {
                    "value": 3.0
                }
            }
        ]
    },
]
```
</details>

It looks like MetaSRA mostly focuses on keywords, so for now the amount of different metadata fields is pretty small (I mostly see age and one other ontology term). Also, MetaSRA does not provide confidence information for this metadata.
