### ISSUE TITLE
Brainstorm and force rank a tagline for landing page

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#290]
### Context

During the High Fi review for the landing page, @Miserlou suggested we brainstorm for a more suitable tagline (copy above the search bar) for the landing page. 

### Problem or idea

Brainstorm for taglines on the ticket. Tag lines need to be short, informative, and preferably have a call to action. (i.e Search) 

For visual reference, the copy will go in the red box:
![screen shot 2018-05-30 at 12 06 38 pm](https://user-images.githubusercontent.com/15315514/40732761-fee5fd32-6401-11e8-9ca2-78d0329e2ce4.png)

### Solution or next step

@Miserlou @cgreene @arielsvn @kurtwheeler @ramenhog @dongbohu @jaclyn-taroni add their tag lines to the ticket.

**Comment by Miserlou** [comment]
Search Millions of Pre-Processed Bioinformatics Samples
Build Bioinformatics Datasets From Millions of Harmonized Samples
Search Millions of Preprocessed Transcriptomic Samples
All The World's Transcriptomic Data, Preprocessed and Labelled For You
Build Ready-To-Use Datasets from Millions of Harmonized Transcriptomic Samples

A few to get us started. Two approaches (potential tests) here, one search based, the other actionalable-dataset based.

**Comment by kurtwheeler** [comment]
Search a Curated Compendium of Transcriptomic Data
Find and Compile Harmonized Transcriptomic Samples
Select a Subset of Our Harmonized Compendium of Transcriptomic Data
A Curated and Harmonized Compendium of Transcriptomic Data at Your Fingertips
Millions of Transcriptomic Samples at Your Fingertips
Millions of Transcriptomic Samples to Make a Discovery With

**Comment by cgreene** [comment]
We should remove this from the Keytar Kurt milestone because the Alex's folks want to help us make the copy on the landing and about pages friendly to multiple audiences. 

I think we need to keep the audience for the tagline, at least initially, to the childhood cancer researchers who want to eliminate the 30% of the time they spend re-processing other people's data. That's the crowd that's going to spur adoption initially.

Things that focus on easy access to other people's data are probably the route to this crowd. @dvenprasad may have more insights here too from her interviews.
