### ISSUE TITLE
Experiments for Usability Evaluations

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#335]
### Context
For usability evaluations, I need to set up a scenario and have the user perform different tasks in the context of the scenario. @jaclyn-taroni  suggested a scenario where the user will have to search for the term "imatinib"

### Problem or idea

We need to ensure that the search term "imatinib" will return at least 6-10 results. 
These are the accessions returned by GEO,ArrayExpress, and SRA for the search term 'imatinib' which is also part of the list in #223 

E-MEXP-433
E-MTAB-2594
E-TABM-585
E-TABM-702
GSE22852
GSE30416

### Solution or next step
We will need to keep a tab on these accessions and make a note whether they are processed or not. 

Also, the number of experiments is on the lower end of what I would like. Would it be possible to explore an alternate scenario?

**Comment by jaclyn-taroni** [comment]
This seems low and incomplete to me. For instance, I would expect [`GSE38310`](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE38310) to be in this list because it is on `GPL6947` which we support: https://github.com/AlexsLemonade/refinebio/blob/dev/config/supported_microarray_platforms.csv#L596.

@dvenprasad can you determine if there might be an error on your end or upstream as part of this list https://github.com/AlexsLemonade/refinebio/issues/223#issuecomment-396944919 ?

**Comment by dvenprasad** [comment]
Okay, that was my bad. They were listed in E-GEOD-XXXX format. 
In addition to the accessions above, these are also part of the list in #222 

E-GEOD-10912
E-GEOD-14671
E-GEOD-15237
E-GEOD-15892
E-GEOD-17480
E-GEOD-1922
E-GEOD-20876
E-GEOD-20987
E-GEOD-21315
E-GEOD-21664
E-GEOD-22433
E-GEOD-22852
E-GEOD-24813
E-GEOD-2535
E-GEOD-28698
E-GEOD-30883
E-GEOD-33075
E-GEOD-34900
E-GEOD-38310
E-GEOD-39335
E-GEOD-43225
E-GEOD-44810
E-GEOD-46928
E-GEOD-51698
E-GEOD-5258
E-GEOD-53202
E-GEOD-53633
E-GEOD-56472
E-GEOD-57800
E-GEOD-57805
E-GEOD-57811
E-GEOD-57815
E-GEOD-57822
E-GEOD-6338
E-GEOD-64762
E-GEOD-7114

**Comment by jaclyn-taroni** [comment]
Is this updated list enough experiments for the evals?

**Comment by dvenprasad** [comment]
Yes, this will be enough for testing.

**Comment by jaclyn-taroni** [comment]
@kurtwheeler will run in staging
