### ISSUE TITLE
Populate Processor table dynamically 

### ISSUE THREAD

**Issue by dongbohu** [AlexsLemonade/refinebio#361]
### Context

According to this conversation:
https://github.com/AlexsLemonade/refinebio/issues/322#issuecomment-400808316

We need to create a YAML config file for each processor (`Salmon Quant`, `Salmontools`, `Tximport`, etc), then inside each processor's corresponding docker container, query versions of programs/packages listed in this config file, and populate these information into `Processor` table in the database.

### Problem or idea

The population process should be done **after** docker images have been updated by the deployment process and Terraform has created RDS instance.

### Solution or next step

(1) Create a YAML file for each processor;
(2) Write a Django management command to read the YAML file and populate the records;
(3) Call the management command inside Terraform after RDS has been created.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by dongbohu** [comment]
Here is the structure of the YAML file for each processor that I have been thinking about:

```
---

# Operating system distribution (such as Ubuntu 16.04, CentOS 7.2, etc)
os_distribution:

# OS-level packages (retrieved by "apt-query")
os_pkg:
  - python
  - r-base
  - java
  - g++
  - etc ...

# Command line programs (retrieved by "<command> --version")
cmd_line:
  - salmon
  - samontools
  - etc ...

# Python packages (retrieved by "pip")
python:
  - Django
  - request
  - etc ...

# R packages (retrieved by R command)
R:
  - tximport
  - etc ...

# Any other package/program category? 
```

@cgreene and @jaclyn-taroni: Please let me know whether it makes sense to you. Thanks.

**Comment by Miserlou** [comment]
@dongbohu - You are saying `retrieved by "pip"` - does that mean that these files will be created dynamically before being loaded in? Or vice versa? This seems like we are significantly increasing the amount of dependencies we have to maintain without any system for checking that they're in sync.

**Comment by dongbohu** [comment]
What I meant is, when the database server and docker container are both up, a management command will be launched inside the docker container to read in this YAML file, retrieve the version information for each processor, build a JSON object, and update the processor records in the database (if necessary).

**Comment by dongbohu** [comment]
Forgot to mention: The YAML files are static.

**Comment by Miserlou** [comment]
You see what I'm saying though - ex, we already have a `requirements.txt` file, and now if we want to update any single requirement we'll have to also manually update (2? 3? 4?) more YAML files. I think this seems like a potential recipe for disaster, since these files are the "source of truth" for the end users, but they don't actually correlate automatically with what the file was actually processed with. I think it'd be better if we had one single source of actual truth, so if the images were built off of these specs, or if the specs were populated automatically from the docker images.

**Comment by dongbohu** [comment]
I see your point. But on the other hand, the JSON environment field in the database is more for the regular users (instead of for developers), so it doesn't have to include all pip packages listed in `requirements.txt`. For example, maybe a user only cares the version of Django that our server is running.

**Comment by dongbohu** [comment]
We can certainly create the `python` section of the YAML file from `requirements.txt`.

**Comment by cgreene** [comment]
Just so I'm clear here - this is specifying the versions of packages that we think need to be user-exposed on a per processor basis. This doesn't have any version information in it. It just specifies the packages we want to get versions of.

I'm not entirely a fan of using `requirements.txt` for retrieval because some of these might be dependencies of the packages in requirements.txt. That's not true now, but it could be in the future.

I do like the format of this file and the specifications of how items are retrieved. I could see an extension of an "other" section that runs some arbitrary command and grabs stderr, but I don't think we have a use case right now, so we can always build that later.

**Comment by cgreene** [comment]
One more small proposal for the implementation. _If_ there is a python: section specified, the python version is retrieved. Also, the same thing for R. Otherwise they are not.

**Comment by jaclyn-taroni** [comment]
The structure LGTM @dongbohu

**Comment by dongbohu** [comment]
Done in PR #481.
