### ISSUE TITLE
Illumina no-op detection

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#535]
Noticed this error while scanning through the code. Wondered how many there were. Only one! Asked Jackie and she says:
> that file should not be no-op'd it's raw data

https://sentry.io/greenelab/staging-refinebio/issues/648682435/

```
We found an Illumina file to NO_OP that we're not set up to process yet. Tell Rich!
```

**Comment by jaclyn-taroni** [comment]
It could be related to the fact that the headers of the non-normalized file (`GSE60102_non-normalized.txt`; [here's the GEO accession](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE60102)) are the sample _descriptions_ rather than the accession numbers or sample names? Related: https://github.com/AlexsLemonade/refinebio/pull/487

**Comment by cgreene** [comment]
😮 ! I filed the issue just as something to track for the future and within an hour there's PR #536! 🎉
