### ISSUE TITLE
Search results should be limited to organisms with QN targets

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#644]
### Context

> At this point, we'll only want to deliver quantile normalized data to users

https://github.com/AlexsLemonade/refinebio/issues/642

### Problem or idea

Since we only want to deliver quantile normalized data to users, and we don't want to show users data we won't give them, we shouldn't show them data that we cannot quantile normalize. We can only quantile normalize data that we have already built a QN target for. Therefore the front end should not expose samples which are from organisms we don't have QN targets for.

### Solution or next step

I'm not 100% sure what the best way to implement this is, so the next step is figuring out a good way to do so..

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by cansav09** [comment]
There are some species that we don't have QN targets for like Yeast that show up as downloadable, but are not actually downloadable. 

Example: [GSE26169](https://www.refine.bio/experiments/GSE26169/expression-data-for-saccharomyces-cerevisiae-oxidative-stress-response)

**Comment by cansav09** [comment]
Further information on this phenomenon: apparently though I clicked the "Add to Dataset" button seen above, and I didn't think it added to my Downloadable dataset (because it still had a `0` badge like above), apparently it DID (sort of) add to my cart. 

I attempted to add this to my cart yesterday. I didn't think it added, but then today I downloaded a separate dataset and ended up with an empty folder and empty metadata file for this dataset. Presumably because it was still added to my cart. 
Note: GSE26169 is the dataset above that is Yeast, that doesn't actually have data that still got added even though it shouldn't have. GSE37418 is a different dataset that I was actually trying to download for another purpose. 

![Screen Shot 2019-04-17 at 10 34 26 AM](https://user-images.githubusercontent.com/23458084/56296392-6724c980-60fc-11e9-904e-12f3bd865a82.png)

**Comment by cansav09** [comment]
@arielsvn It is unclear to me how much of this is a front-end issue, so you may want to read through my comments to see what may or may not need to be fixed on front-end.

**Comment by arielsvn** [comment]
This should also be solved with https://github.com/AlexsLemonade/refinebio/issues/1162, without it we don't have information on the samples that are downloadable in the FE. 

I'm gonna close this to keep track of the issue in #1162
