### ISSUE TITLE
Create API documentation

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#687]
### Context

We do not currently have API documentation.

### Problem or idea

@kurtwheeler has mentioned using [Swagger](https://swagger.io/solutions/api-documentation/) to create API documentation.

### Solution or next step

Tagging @kurtwheeler @Miserlou @dongbohu 

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
What's the use case for this? The API is already self-documenting and explorable: https://api.refine.bio It's also an extremely simple API - list the objects. Get an object. The only tricky part is the API tokens required for starting dataset processing, which is documented here: 
https://api.refine.bio/token/ We can expand this docstring based documentation as well.

I've used Swagger on top of DRF before but never saw the benefit. I think this would be better implemented as a tutorial about how to do something with the API rather than adding any additional documentation layer.

**Comment by jaclyn-taroni** [comment]
> I think this would be better implemented as a tutorial about how to do something with the API rather than adding any additional documentation layer.

That would be fine with me, I meant "documentation" in the broadest sense. I put Swagger here because @kurtwheeler mentioned it, but if you two decide it is better to go the tutorial route, that sounds good and we can update this ticket accordingly.

In addition, I believe @dvenprasad thinks our users would greatly benefit from both Python and R API wrappers and mentioned the [Harmonizome project](http://amp.pharm.mssm.edu/Harmonizome/documentation) from the Ma'ayan Lab as an example. We can track this here on this issue or file additional tickets, what would you prefer?

**Comment by cgreene** [comment]
@Miserlou : How does one find out about the self-documenting and explorable API and how do they learn about the tokens? Does that information appear anywhere in the documentation?

**Comment by kurtwheeler** [comment]
I'm not sure swagger is necessary, I had just thrown it out there because I am potentially excited that catching on, but I do think we need to improve our API documentation. Some of it could just improving the docstrings for views, which is how the API is self-documented. It's a bummer that they won't render HTML though, I just tested. I also think that a brief overview of the data model could be helpful.

I think a tutorial would be sufficient if it covered the data model, covered the API key retrieval/usage, gave a few examples, and linked to the self-documenting API.

**Comment by kurtwheeler** [comment]
We've decided that the API docs could be a bit more verbose and approachable. As the primary consumer of the API via his frontend work, @arielsvn is going to take a crack at improving our current documentation.

**Comment by arielsvn** [comment]
Closed by https://github.com/AlexsLemonade/refinebio/pull/1330
