### ISSUE TITLE
We need a larger and/or non-burstable foreman instance

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#854]
### Context

The foreman process died last night. The last heartbeat message was:
```
2018-11-20 03:11:15,476 i-08bd0a139def7f5f2 data_refinery_foreman.foreman.main INFO: The Foreman's heart is beating, but he does not feel.
```
and the last log message was at `2018-11-20 03:21:05,301`.

Oddly the docker container was still running and the python process seemed to still be going:
```
ubuntu    2404  6.9 21.6 868232 220156 pts/0   Ssl+ 00:16  64:43 python3 manage.py retry_jobs
```

However the heartbeat was done and after queuing up some survey jobs, they never got queued. I restarted the foreman and it queued more than 2.5k processor jobs, so clearly there was something for it to do but it wasn't trying to do so.

I think it may be related to CPU credit usage:

![image](https://user-images.githubusercontent.com/4026833/48788704-5db44400-ecb9-11e8-85e0-0992844f6dd7.png)

![image 1](https://user-images.githubusercontent.com/4026833/48788713-64db5200-ecb9-11e8-8f76-18ba6ed18be0.png)

As you can see our CPU utilization drops right at the same time that we run out of CPU credits which is right around the time the foreman stopped logging.

### Problem or idea

I'm not sure why the foreman stopped working without its process dying. It's not entirely clear what happens when you run out of CPU credits, AWS doesn't actually say in their documentation. The best guess I have is that the main loop got starved of resources and died without actually crashing the main python process? Something like that? I don't really know.

### Solution or next step

I think we need a non-burstable instance, it may need to be slightly larger as well.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
I stilllllllllllll don't actually think that's really what's going on. Although I'm more uncertain that I was before. I just don't believe that there's an instance type that will start just killing processes if you _actually use them_ too much. Although the timing is something else. Looks like we'll see if the same behavior happens when we run out of CPU credits again.

Either way, our jobs load is going to be so high that this is probably to much work to run the Janitor on an `t*` anyway, it's just move it to a `c*`/`m*` with a bit more oomph.

Other notes:

a) Why hasn't this happened before?
b) Why didn't it recover automatically?
c) The foreman processes should be run with something like upstart/monitor so that it doesn't require a manual reset.

**Comment by Miserlou** [comment]
We were able to reproduce this behavior. It was the CPU credits. Crazy stuff. Fix pushed.
