### ISSUE TITLE
API should remain up if a deploy fails

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#884]
### Context

https://github.com/AlexsLemonade/refinebio/issues/883

### Problem or idea

Sometimes deploys are going to fail. We're doing our best to make this as rare as possible, but it's gonna happen from time to time. When it does, our website should stay up.

### Solution or next step

We should make sure that our website stays up even when deploys fail.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
I still don't understand what exactly the problem was. Was the API instance taken down during the deploy failure?

A few things to note here:
* Friday Afternoon Production Deploys. No. Never. Stop. We already learned this lesson. No. Bad. Don't. Not good.
* StatusCake Slack Notifications are not enough to let us know that this is happening. It did "notify"
 us, but nobody actually saw the notification so it didn't work anyway.
* We should consider B/G deployments for specific components of the architecture so this doesn't happen.
* NO FRIDAY AFTERNOON PRODUCTION DEPLOYS

**Comment by kurtwheeler** [comment]
We haven't had the API taken down by a failed deploy in a long long time. I think this has been addressed by a number of improvements to our deploy processes.
