### ISSUE TITLE
Normalize "Description" Fields // Make Samples Full-Text Searchable

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#95]
In order to make our database maximally useful for researchers, we need to have all of the information we have about a sample full-text searchable.

This means a) normalizing all (or most) of the possible "description/about/comment" fields for a given input and b) making all of the data we have for an input full-text searchable.

Additionally, we maybe need to learn more about how to process and execute ElasticSearch queries and [associate with our Postgres](https://github.com/zombodb/zombodb) instance.

Example: Find all samples associated with Ewing Sarcoma.

**Comment by Miserlou** [comment]
Zombo doesn't work with RDS (currently), and it all seems like PG's [full text search capabilities](https://www.compose.com/articles/mastering-postgresql-tools-full-text-search-and-phrase-search/) may actually provide just enough of the functionality we need given our example use cases.

**Comment by jaclyn-taroni** [comment]
Based on our meeting a few weeks ago, my understanding of the main motivation behind this ticket boils down to: 

**Some information is always going to be required (e.g., submitter contact information) in order to submit data to a government-run repository (termed "mandatory information" below). It might not be called the same thing at every repository, but it can generally be considered equivalent.**

([Here's some information](https://www.ebi.ac.uk/fg/annotare/help/index.html) about what submitters need to prepare to submit a data set to ArrayExpress using Annotare and [here's information from GEO](https://www.ncbi.nlm.nih.gov/geo/info/spreadsheet.html) about submitting using the GEOarchive spreadsheet-based submission method.)

I've made a table of a few examples based on some cursory browsing of ArrayExpress, GEO, SRA and ENA (mostly through the web interface). (This should be considered a _first pass_ that may change once we look at more examples.)

![screen shot 2018-02-06 at 8 36 48 am](https://user-images.githubusercontent.com/19534205/35862264-0e0046de-0b19-11e8-8d71-7afcb846c2b1.png)

The sample attributes or characteristics are not going to be normalized -- some studies in human may provide age while others do not. Normalizing these fields/data is an open research question (see [MetaSRA](http://metasra.biostat.wisc.edu)). By keeping things on a _per experiment_ basis for browsing, I think this should avoid some "non-normalized" concerns. As a user, when I look at an experiment I might ultimately want to know if age was included in the sample metadata and what the distribution of age values looks like. That is likely to be more valuable to me than looking at the age values associated with each sample individually.

If you provide example JSON or XML files from each source at different levels (experiment/study/run/etc.) for a several experiments, I am happy to help sort through the mandatory information normalization bit.

**Comment by jaclyn-taroni** [comment]
I'll also note here that what is probably most valuable for full text searching are the title of the experiment and the study abstract.

**Comment by Miserlou** [comment]
I think this is all _mostly_ taken care of in the refactor , the only thing outstanding is the study abstract from SRA, which will be mapped to the Experiment description if possible, else will be separated out into its own table.

**Comment by cgreene** [comment]
Connected to #165.

**Comment by Miserlou** [comment]
Closed via various PRs.
